### ISSUE TITLE
Add linking to developer dashboard from documentation

### ISSUE THREAD

**Issue by nickfreemandesign** [GoogleChrome/developer.chrome.com#1014]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Hey there. Pretty straight forward (hopefully reasonable) ask. As a developer, I have a horrible time finding the dashboard to redeploy my app. One thing I can easily find my way back to is the docs. From there futility starts to kick in as there is nothing that says "Go To Dashboard" to be found

**Comment by robdodson** [comment]
Tagging @AmySteam as this may be related to some of the work she's doing.

@dotproto, @awfuchs, Amy — do y'all have any thoughts on which page would be the best to include this link?
@nickfreemandesign any suggestions? 😁

**Comment by dotproto** [comment]
First thought is that we could add a "Chrome Web Store Developer Console" link to the footer. I wish we could shorten that, but while I often use "CWS" in conversation, our naming guidelines aren't nearly as casual ;)

The second easiest link location that leaps to mind is the small text blurb at the top of https://developer.chrome.com/docs/webstore/. I hesitate with this option, though, because I don't have a great idea on how to integrate a dashboard link into the sections summary copy.

A less precise solution is to adopt the pattern of including link to the developer console on the first mention of this term in a given CWS page as seen on the [Register as a Chrome Web Store developer](https://developer.chrome.com/docs/webstore/register/ page). We could make a point of integrating one such link in each page under the "Publish your extension" section.

**Comment by nickfreemandesign** [comment]
Thanks for picking this up @robdodson. A few thoughts come to mind, one of them definitely in line with Simeon's thought to add it to the footer. Would the name "Developer Dashboard" suffice within the context of the extension docs? It seems to be written as such on the page's meta data, though I'd understand if that draws confusion about the other various Google developer dashboards out there.

![image](https://user-images.githubusercontent.com/12129271/127596366-8ada88c6-5346-49f7-af18-211e010cefa1.png)

Another thought is to add something a bit more salient, in the [overview of the home page](https://developer.chrome.com/), allow the user to navigate from there. This makes sense to me because developers either navigate to this page because they either want to build something, or they already have something deployed that they are iterating on. 

![image](https://user-images.githubusercontent.com/12129271/127596624-4cb4d2c3-e6ef-4b0e-a16f-752f60ea4f61.png)

And lastly I'd say it makes sense to add a link in the home page to the [Chrome Web Store docs](https://developer.chrome.com/docs/webstore/), or at least immediately within a doc under the "Publish your extension" category. At a glance, I'd say the docs "Publish in the Chrome Web Store" is a prime candidate to contain a hyperlink to the dash.

![image](https://user-images.githubusercontent.com/12129271/127597334-dcfb9c28-d43f-45f6-b999-d9576db38ba7.png)

I hope this helps! Cheers y'all and thanks for all that you do!

**Comment by robdodson** [comment]
I don't think that we would add the button to the homepage because the site covers a number of other Chrome related projects/features outside of Extensions / Chrome Web Store.

I do think that having one of the docs link to the dashboard makes sense. Perhaps @AmySteam is already working on this as part of her docs updates? I'll ask.
