### ISSUE TITLE
[extensions][getstarted] - green button in final code is not 'clickable' / does nothing

### ISSUE THREAD

**Issue by con-dog** [GoogleChrome/developer.chrome.com#1018]
Go to https://developer.chrome.com/docs/extensions/mv3/getstarted/
Follow tutorial or download zip
Open new tab to run extension
Green button can not be clicked/does nothing

OS Win10
Chrome Version 91.0.4472.164

**Comment by con-dog** [comment]
Turns out it's as the tutorial isn't updated to manifest v3 entirely

**Comment by AmySteam** [comment]
Hi @con-dog, I was wondering what website you were on when you clicked on the popup? I tried to run it in a newtab or chrome://extensions as well and it didn't work, but if you try it on any other page, like for example [getting started](https://developer.chrome.com/docs/extensions/mv3/getstarted/) , it should change the page background color to green. 

Hope this helps! Amy :)

**Comment by dotproto** [comment]
This appears to be a somewhat common point of confusion. Extensions cannot script the `chrome://extensions` or any other `chrome://`  page due for abuse reasons. We don't currently call this out in the tutorial, so developers try to test the extension on the chrome://extensions page.

We should revise this guide to explicitly call out that chrome:// pages cannot be scripted and gracefully recover when if injection fails because the extension can't access the target page.
