### ISSUE TITLE
Authors page

### ISSUE THREAD

**Issue by petele** [GoogleChrome/developer.chrome.com#1019]
Can we get an authors page similar to https://web.dev/authors/petelepage/

**Comment by robdodson** [comment]
Hm I wonder why we never did this. We have designs for it 😅

@MichaelSolati do you know if all the plumbing is in place for us to generate these pages?

![image](https://user-images.githubusercontent.com/1066253/127586954-32f9c747-e21d-4449-8599-82f254263a1f.png)

**Comment by MichaelSolati** [comment]
I think most of the plumbing is in place for this so i can definitely do this. I think we did discuss this and had decided not to do it, but i can aim to land this by next week.

**Comment by samthor** [comment]
I had a vague opinion early on that since dcc was more based around
reference docs (the single author is less important/relevant, should be
updated by all - not blog posts), we should de-emphasize this kind of page.

e.g., obviously Kayce has done a ton of work on all the DevTools pages, but
they're living reference documents (akin to say MDN).

I appreciate this doesn't quite match the blog. That's my 2c, I don't
really have an opinion more than this.
