### ISSUE TITLE
Update MV3 XHR CORS page to talk about fetch()

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/developer.chrome.com#1158]
[The XHR page](https://developer.chrome.com/docs/extensions/mv3/xhr/) is informative but in MV3 we basically want you to use `fetch()` instead, so we should talk about CORS in that context and link to the MV2 page if people still want to know about XHR.

**Comment by tophf** [comment]
* It should probably say that cookies are sent automatically to sites for which the extension has host permissions.
* Since XMLHttpRequest is still usable inside an [offscreen document](https://developer.chrome.com/docs/extensions/reference/offscreen) some residual info about it should probably remain at the bottom.

**Comment by AmySteam** [comment]
@jpmedley @IanStanion-google 
Was this addressed in any of your PR's? If so can you close this issue?

**Comment by jpmedley** [comment]
This is what #6394 does, with the exception that it does not contain a link to MV2 documentation because it will simplify things when we remove the MV2 documentation. The new version of the document refers to XHR and links to the MDN reference on it.

@samthor, long time no see. Is there anything we need to add about CORS to the existing document?

**Comment by samthor** [comment]
I can't really provide more context. I can't remember.

If I had to answer, it might be saying "you're not immune to CORS in an extension", but this is general web advice rather than extensions specifically.

**Comment by AmySteam** [comment]
Fixed in #6813 and #6521
