### ISSUE TITLE
code snippets are hard to read

### ISSUE THREAD

**Issue by vapier** [GoogleChrome/developer.chrome.com#130]
let's look at this page as an example:
https://developer.chrome.com/docs/extensions/reference/events/#declarative

all the code snippets are hard to read because of the monospace font, the font size, and the tight cropping used on the snippet element.  plus, Chrome APIs tend to be pretty verbose with their namespaces exacerbating the problem.

i don't think this is an isolated incident ... these code snippets are pretty emblematic of code examples on the site.

maybe an easy fix would be to use a slightly smaller font (in my experience this is pretty common in reference docs), and then allow the boxes to take up more horizontal space.

**Comment by robdodson** [comment]
@vapier can you share a screeshot of which snippet you find hard to read (the hash anchor doesn't seem to work for me)?

Taking a glance, snippets like this seem ok to me but I realize this sort of thing is a bit subjective :)

![image](https://user-images.githubusercontent.com/1066253/105113241-64959780-5a79-11eb-8857-2883427fabb6.png)

---

The snippets that are inside of list bullets _do_ seem a bit jammed up I think

![image](https://user-images.githubusercontent.com/1066253/105113337-94dd3600-5a79-11eb-8325-ab245d8f013d.png)

---

In the tabled sections I find the code a bit hard to read because the font is quite small. So in this one `(rules: Rule[]) => {...}` is a bit difficult for me to make out.

![image](https://user-images.githubusercontent.com/1066253/105113404-b5a58b80-5a79-11eb-803f-d96084490043.png)

**Comment by vapier** [comment]
CrOS on my pixelbook renders these with less space so i don't get to see as much code as your screenshots do.  i haven't changed the defaults at all here.

![screenshot](https://user-images.githubusercontent.com/176950/105126111-09c96380-5aac-11eb-8ab8-2e4a136570ee.png)

**Comment by robdodson** [comment]
ah yeah I bet it's because we're using the system font for monospace and it may be wider on CrOS.
Also these code blocks are nested inside of a list which is scrunching them up some.

@dotproto @awfuchs what do y'all think of removing the list so the code blocks have more room?
