### ISSUE TITLE
The "background.persistent" key cannot be used with manifest_version 3. Use the "background.service_worker" key instead.

### ISSUE THREAD

**Issue by dkokic** [GoogleChrome/developer.chrome.com#156]
**Describe the bug**
According to the documentation of the manifest.json v3, it should be possible to set the property "background.persistent".

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an extension with the manifest.json v3 and set the "background.persistent" to a boolean value (e.g. false)
2. Load the extension in a Chrome browser
3. Chrome responds with an error popup 

**Expected behavior**
The extension should not cause an error on loading into Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/213902/103438784-1ab65000-4c37-11eb-8c3e-fd594c4829c7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Here21** [comment]
+1

**Comment by scglenn** [comment]
+1

**Comment by dotproto** [comment]
Deleted +1s. Please use [Github's Reactions](https://docs.github.com/en/rest/reference/reactions) feature for this use case.

As the Chrome error indicates, `background.persistent` cannot be used in MV3 extensions. We've made a number of updates to the MV3 documentation since this bug was originally filed, most notably in this case the [MV3 version of the Getting Started guide](https://developer.chrome.com/docs/extensions/mv3/getstarted/). Unfortunately, the original bug report didn't state which pages implied it was allowed. I tried searching through the docs source a couple different ways, but I didn't see any current a reference to this property.

@dkokic, can you verify if we've updated the docs to address your concerns?

**Comment by dotproto** [comment]
Quick update to note that I am going to close out this issue if we don't have any more discussion on it in the next 7 days.
