### ISSUE TITLE
Fix examples in "Getting started"

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#187]
The examples on the MV3 [Getting started](https://developer.chrome.com/docs/extensions/mv3/getstarted/) page have not been fully updated from the original MV2 versions.

This was converted from MV2 docs and has a remaining issue:

- The example around line 300++ was changed for MV3 from tabs.executeScript() to scripting.executeScript() using a function... However this is not tested and probably doesn't work -- needs fixing.
- This was raised as a review comment in the earlier repo's PR/512
- The original comment was "I don't think this will work because the variable color will be undefined at execution time. That's because the body of the function is executed asynchronously as a content script, so the color variable on line 301/299 will not be in scope."
- In that same review, rdcronin@ pointed to lines 67-69 as incompatible with MV3.

**Comment by charliejl28** [comment]
+1. 

Also the very initial `Add instruction` section does not work  with this proposed manifest.json:
```
{
  "name": "Getting Started Example",
  "version": "1.0",
  "description": "Build an Extension!",
  "background": {
    "scripts": ["background.js"],
    "persistent": false
  },
  "manifest_version": 3
}
```
because MV3 does not support the `background.scripts` key from my understanding. Copy + pasting the example as is yields this error when reloading the unpacked extension:

![image](https://user-images.githubusercontent.com/4616805/104538660-27d92480-55d1-11eb-9c9f-27fa76d000e1.png)

Changing the `manifest_version` value to `2` resolves the error

**Comment by dotproto** [comment]
Opened GoogleChrome/chrome-extensions-samples#543 to update the underlying sample. Working on updating the copy now.
