### ISSUE TITLE
Spanish Not Work

### ISSUE THREAD

**Issue by Juandieruiz** [GoogleChrome/developer.chrome.com#1986]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![spanish](https://user-images.githubusercontent.com/77864382/150367997-29379659-00f9-4395-b11b-d504115c40ba.png)
![spanish](https://user-images.githubusercontent.com/77864382/150368045-1e5b29bf-713c-4497-ba06-90fa5bc59f48.png)
**Desktop (please complete the following information):**

 - Google Chrome & Brave

**Additional context**

**Comment by jeffposnick** [comment]
Apologies, but it's not clear what the underlying issue is that you're reporting.

I did try switching to Spanish using the popup at the bottom of the page, and while not all of our current content has a Spanish-language translation, the content that does have a Spanish equivalent shows the translations.
