### ISSUE TITLE
Build.md

### ISSUE THREAD

**Issue by Fizie92** [GoogleChrome/developer.chrome.com#2002]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Linksforyou** [comment]
Hi

Thank you verry much for your answer.
To be hunnest i dont know verry much im teachin myself by just try and figure it out.
I had this great idea to build a website and start with affilate marketing i love challanges and i really like this, but im not that good in english i understand allot but when it comes to building therms it freaks me out some times lol!

So i am just a amature and i started to build my website on a platform that makes it allot easyer with those tools.
I have already learnd allot by all those on obstikels cause its harder then i thought.
Took allot of time to fix it on my own and figure it out and thats fine but this problem i just cant fix it and really holding me back cause im having this probleem for weeks now and i think i know what it is and how it happend but every time that ik think that i fix it its keep coming back.
Sorry for this long story haha but this is the situation and i hope i can explain it well:

Im mostly work on my chromebook but my Phone is connected on it so now i have the problem on both.

I made a dom mistake by delete de lunix app on my chromebook.
I had to much apps on my chromebook so it started giving problems and i had to clean up
So then i nodist that all my certificates where gone and my website wassent safe anymore and had problems with dns records that where gone to.
So for me it was panic i made a dom mistake and i did not know anything.
Now i have fixed my website and de rest of the problems the only thing is i have my https frist on in safe browser.
I have the ssl certificates but i dont really know what the best api key is cause that was gone to i tryed some and it looks like i dont have problems but the most sites are protected and have https and then i go to the next site and then it says its not protected and missing the https first in Chrome.
Even if i log out of Google chrome and only use other google service this is keep coming back.
My website was already build in html site so i can add allot easy tools by edding codes or urls so i use the embeded tool on page or in the option of html in head tag.
So maybe this is stupid question but where do i but the link you send me?
I hope you can understand my long bad english story and i hope to hear from you.
Thank you.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
From: Fizie92 ***@***.***>
Sent: Sunday, January 23, 2022 7:33:28 PM
To: GoogleChrome/developer.chrome.com ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GoogleChrome/developer.chrome.com] Build.md (Issue #2002)


⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   OS: [e.g. iOS]
  *   Browser [e.g. chrome, safari]
  *   Version [e.g. 22]

Smartphone (please complete the following information):

  *   Device: [e.g. iPhone6]
  *   OS: [e.g. iOS8.1]
  *   Browser [e.g. stock browser, safari]
  *   Version [e.g. 22]

Additional context
Add any other context about the problem here.
