### ISSUE TITLE
The MV3 migration guide recommends jsdom, but it cannot be used in browsers out of the box

### ISSUE THREAD

**Issue by CallumBasham** [GoogleChrome/developer.chrome.com#2290]
The page explains that the package '_jsdom_' can be used with _Service Workers_ on _Chrome Extensions_, however there is **no clear or provided method of implementation**, and the **JSDOM developers do not actually support working with Service Workers** on Chrome and are therefore unable to assist with implementation problems. 

**See the Issue on JSDOM git here:** [JSDOM ISSUES](https://github.com/jsdom/jsdom/issues/3315)
**Page in question on Google Docs:** [Google Developer Docs](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/
)
Essentially as Chrome Extension Developers, we would simply like to know how to import a DOM library into a service worker's backend so that we can parse HTML without coding our own excessive libraries for doing so when they already exist.

**Comment by guest271314** [comment]
Technically the requirement is possible using Native Messaging. In this case a Node.js Native Messaging host https://github.com/simov/native-messaging can be used for JSDOM. The result of JSDOM can then be communicated to the MV3 `ServiceWorker`. 

I do concur that the documentation is misleading, and out of place in the context, with regard to the paragraph

> Libraries such as [jsdom](https://github.com/jsdom/jsdom) can be used to emulate a typical browser window environment, complete with DOMParser, event propagation, and other capabilities like requestAnimationFrame. Lighter-weight alternatives like [undom](https://github.com/developit/undom) provide just enough DOM to power many frontend frameworks and libraries.

**Comment by guest271314** [comment]
Here you go https://github.com/guest271314/jsdom-extension/tree/main.

**Comment by chintannp** [comment]
@AmySteam , Any update on this?

**Comment by guest271314** [comment]
@chintannp Did you test the extension linked at https://github.com/GoogleChrome/developer.chrome.com/issues/2290#issuecomment-1086660435?

**Comment by dotproto** [comment]
There's some additional discussion in jsdom/jsdom#1284.

I had assumed that adopting jsdom would be easier than it seems to be. The project's README states that "jsdom has some support for being run inside a web browser, using [browserify](https://browserify.org/)" and later notes that "jsdom works well inside a web worker." 

We should update the migration guide to either recommend a different library or link to a working demo. If we recommend using another library, the resource we recommend should be usable in a web worker context without a build step. After a brief search, it appears that [linkedom](https://github.com/WebReflection/linkedom) may be one such library. If we link to a demo, consider adding the demo to the chrome-extension-samples repo.

**Comment by guest271314** [comment]
> We should update the migration guide to either recommend a different library or link to a working demo.

https://github.com/guest271314/jsdom-extension/

>  If we link to a demo, consider adding the demo to the chrome-extension-samples repo.

In which directory?

**Comment by dotproto** [comment]
@guest271314, I am hesitant to go with the contents of that repo because it contains a static version of a modified version of the generated output of another project.

While the premade, MV3 service worker compatible version of `jsdom.js` included in this repo is very easy for an extension developer to use, keeping this file up to date with the upstream project would require continual manual work for maintainers and there's no easy way for developers using the static file to verify the integrity of the packaged code. When I suggested that we "link to a working demo," I was imagining that the demo project would use Node.js and npm to fetch the jsdom package and use Browserify, Webpack, or another appropriate build tool to generate the distributable asset that an extension developer would include in their extension. Based on your comments in [jsdom #1284](https://github.com/jsdom/jsdom/issues/1284), though, it sounds like this isn't as easy or straightforward as I had expected.

At the moment I'm leaning towards the view that this approach introduces too much complexity for extension developers not already comfortable with the Node ecosystem. I'd like to see if linkedom might be as easy downloading the right file from an npm CDN like UNPKG or jsDelivr and using `importScripts()` to load the file in a service worker.

**Comment by guest271314** [comment]
Technically, it is possible to fetch `node` executable (and `npm`) for the purpose of running JSDOM in a Node.js Native Messaging host, then truncating the `node` executable to `0`. Otherwise, the claim must have been without testing whatsoever.

**Comment by guest271314** [comment]
>  I was imagining that the demo project would use Node.js and npm to fetch the jsdom package and use Browserify, Webpack, or another appropriate build tool to generate the distributable asset that an extension developer would include in their extension.

And yet this is still in published in https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/

> Libraries such as [jsdom](https://github.com/jsdom/jsdom) can be used to emulate a typical browser window environment, complete with DOMParser, event propagation, and other capabilities like requestAnimationFrame. Lighter-weight alternatives like [undom](https://github.com/developit/undom) provide just enough DOM to power many frontend frameworks and libraries.

The claim was never tested before publishing and should be immediately removed from the documentation.

**Comment by AmySteam** [comment]
The new migration guide has been rewritten. This issue is no longer relevant.

https://developer.chrome.com/docs/extensions/migrating/
