### ISSUE TITLE
Avoid hard wrapping

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/developer.chrome.com#245]
Could I persuade you away from adding line-breaks to markdown for wrapping purposes?

Negatives to the 100 char wrap:

* You have to remember to do it.
* You need to do it manually or get a tool for your editor.
* A one-word change can turn into a diff of many lines.
* Makes it difficult to search for a term if the term is newline split in places.

What are the pros?

**Comment by robdodson** [comment]
> Could I persuade you away from adding line-breaks to markdown for wrapping purposes?

Is this a linter issue? To my knowledge we're not formatting the markdown but I could be mistaken.

I believe the wrapping is something that the tech writers (maybe joe?) have requested in the past because they find it difficult to scan a github diff if the lines  are long. But I'm fine with changing it if @kaycebasques is.

**Comment by petele** [comment]
My $0.02 -- Over the last year or so, GitHub has significantly improved diff support for long lines. In the past, you knew the line changed, but not *what* in the line changed. That's why we required them on WebFu.  Personally, I prefer with line breaks, but I no longer feel strongly about it.

**Comment by samthor** [comment]
I don't think this rule is enforced anywhere. If it is we can turn it off. But I'm closing this issue from that point of view.

I personally write a sentence per line and would prefer that going forward, but I'm not going to force one way or anoter.
