### ISSUE TITLE
CSP page seems to be missing in both MV2 and MV3 docs sections

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#247]
While diagnosing a number of 404 problems in the docs corpus, discovered that links to the CSP page (previously at .../extensions/contentSecurityPolicy on the old server) are 404 because the page is indeed missing.

This page (potentially with manifest version differences) is expected to exist at the following locations:

- /docs/extensions/mv2/contentSecurityPolicy
- /docs/extensions/mv2/contentSecurityPolicy

But no such directory exists. Also have tried grepping across the corpus for text included in the file, with no hits.

**Comment by cleytontiagosorinho** [comment]
Bom

**Comment by jpmedley** [comment]
@dotproto There are no mentions of contentsecuritypolicy anywhere in the extensions docs. Is that because this is handled by the `permissions` key in the manifest?

**Comment by jpmedley** [comment]
Just found it. The links are still broken.

**Comment by jpmedley** [comment]
I found the [missing page](https://web.archive.org/web/20210505021356/https://developer.chrome.com/docs/apps/contentSecurityPolicy) on the web archive. This is missing because at some point the extensions page was taken down and the URL was redirected to a Chrome Apps page.

@dotproto, can the page I linked to be reused as is for extensions or does it require changes?

**Comment by jpmedley** [comment]
This is being consolidated under #163
