### ISSUE TITLE
Layout Issue at developer.chrome.com on Safari 15.3

### ISSUE THREAD

**Issue by henrihelvetica** [GoogleChrome/developer.chrome.com#2598]
**Describe the bug**

Content layout issue, positioned over the hero image at this address: 
https://developer.chrome.com/blog/insider-april-2022/

**To Reproduce**

1. Go to https://developer.chrome.com/blog/insider-april-2022/

**Screenshots**
![Screen Shot 2022-04-13 at 9 25 50 PM](https://user-images.githubusercontent.com/50970808/163298534-54061986-d1a9-4d8b-a7f8-a59fad0d192b.png)

**Expected behavior**
Content below the hero image as below screen shot. This was taken with Safari version 14.0.1 (16610.2.11.1.3), macOS v11.0 (20A2411) to offer insights. 

**Screenshots**
![Screen Shot 2022-04-13 at 21 40 12](https://user-images.githubusercontent.com/50970808/163298826-aa462be3-41bf-4e19-a2c5-5662066ae3ff.png)

**Desktop (please complete the following information):**
 - macOS: 12.2.1 (21D62)
 - Safari 
 - Version 15.3 (17612.4.9.1.8)

**Additional context**
n/a

**Comment by jeffposnick** [comment]
This is harder to debug because I can only reproduce it on Safari 15.3, which I can't install on an actual Macbook right now, but is available on BrowserStack.

Anyway, the issue seems to be that the parent `<div>` which wraps the hero image should have a height of 480px, and does have that height on other blog pages in Safari 15.3 as well as in other browsers, but on [that page](https://developer.chrome.com/blog/insider-april-2022/), it only has a height of 288px (at least at the viewport size I was testing on). This causes the next section's text to get laid out incorrectly, and also causes the hero image to be a bit distorted:

![Screen Shot 2022-04-14 at 12 09 13 PM](https://user-images.githubusercontent.com/1749548/163430439-4c09ed89-094e-4cf9-911f-94f4467ef485.png)

I took a look at the underlying image, and it appears to be loaded correctly in Safari 15.3 as a PNG with an appropriate size from our image CDN. But it does have the `decoding="async"` and `loading="lazy"` attributes, and I wonder whether those might interact poorly with Safari 15.3 in some way.

I'd like to test more with various combinations of image attributes to see what role they play in triggering it, but only being able to reproduce this on BrowserStack is slowing me down.

Fortunately, I can't reproduce the issue on anything other than desktop Safari 15.3, and I can't reproduce it for any other blog pages, so hopefully this is not something widespread that will bother many readers.

**Comment by henrihelvetica** [comment]
It's an odd one since it was fine on both an older version of Safari, and newer version than mine.  And this was discovered only because I'm using a brand new laptop (just cracked it open). I sense this might vanish w/ an OS update. The layout is as expected in **Safari Tech Preview,** Release 143 (Safari 15.4, WebKit 17614.1.7.7). I shared it on twitter to make sure I wasn't the only with the bug.

**Comment by henrihelvetica** [comment]
Added, possibly related and didn't create an issue, but this would happen when click/dragging the hero image in my current version: 15.3 (17612.4.9.1.8). You might have mentioned it. 

![Screen Shot 2022-04-13 at 9 26 40 PM](https://user-images.githubusercontent.com/50970808/163432510-88065caa-ab3b-4333-926a-c947cf4f313f.png)
