### ISSUE TITLE
Developer blog RSS does not work in slack - probably because it does not validate :(

### ISSUE THREAD

**Issue by grzeg1** [GoogleChrome/developer.chrome.com#2680]
Thank you for corrections. Unfortunately it seems not to be enough as there are still a few things that do not validate.

[https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdeveloper.chrome.com%2Ffeeds%2Fblog.xml](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdeveloper.chrome.com%2Ffeeds%2Fblog.xml)

Probably the most important is: line 590, column 38: Two entries with the same value for atom:updated: 2022-04-13T00:00:00+00:00 (3 occurrences) 

But there are also other.

Would be great if you could fix them as well so that readers can parse the feed properly.

_Originally posted by @grzeg1 in https://github.com/GoogleChrome/developer.chrome.com/issues/2541#issuecomment-1107797802_

**Comment by jeffposnick** [comment]
The [W3 docs for Atom](https://validator.w3.org/feed/docs/atom.html#:~:text=Generally%2C%20different%20entries%20in%20a%20feed%20will%20have%20different%20updated%20timestamps.) read:

> Generally, different entries in a feed will have different updated timestamps.

But that does not sound like a hard requirement, and the feed validation link you provided outputs **This is a valid Atom 1.0 feed.** There are some recommendations listed, but they all have to do with the HTML content of the articles embedded in the feed, and I don't think we're going to try to make changes to that HTML.

So... I'm not exactly sure why your Slack integration isn't working, but the feed does currently validate and work in, e.g., https://feedly.com/

If you can point to a specific error message reported by the Slack integration about a failure, then we can try to address that, but otherwise I'm going to close this issue.

**Comment by grzeg1** [comment]
Below is an explanation I got from Slack support. I hope you find it helpful. Seems it's all about duplicate dates. Would be great if you could change it.


The RSS feed may be indicated as valid, but the Slack RSS app has additional requirements, mostly around dates, for the RSS feed such as:

- There must be a supported data tag.
- Items cannot be listed out of sequence.
- Duplicate dates cannot exist.
