### ISSUE TITLE
Stupidity behind slowing down JS timers (setTimeout & setInterval)

### ISSUE THREAD

**Issue by PELock** [GoogleChrome/developer.chrome.com#304]
I would like to ask what is the rationale behind breaking the API of setInterval() and setTimeout() in Chrome?

This is a crazy idea to make the standard functions behave differently than it supposes to work.

Imagine this kind of throttling in Windows or Linux standard APIs like for example SetTimer() it would have tragic consequences. Linus Torvalds would shred you to pieces if you ever tried to introduce something like this in Linux.

What kind of research has been done to make those changes?

What consequences will it have?

1. People will stop using those APIs and will start to use some hacky solutions (eval()-ed Workers for example, Blob created Workers etc.).

2. People will stop trusting the Chrome platform to build reliable apps, how can you trust a platform, where there is some hidden actor manipulating the API behavior?

This is a terrible design idea and battery life isn't worth breaking *any* API.

**Comment by robdodson** [comment]
@PELock please be respectful when communicating on this project and abide by our [code of conduct](https://opensource.google/docs/releasing/template/CODE_OF_CONDUCT/).

Using phrasing like "stupidity" and "Linus Torvalds would shred you to pieces" comes across as disrespectful. I'm going to lock and close this issue because it's not the right forum for discussing this topic. If you have an issue with Chrome's implementation please respectfully file a bug at https://crbug.com.
