### ISSUE TITLE
why not enable github discuss?

### ISSUE THREAD

**Issue by calidion** [GoogleChrome/developer.chrome.com#3282]
I have issue with favicon in extension v3.
I googled and found nothing useful.
I enabled favicon  with v2 but found no document or discuss with v3.

**Comment by rachelandrew** [comment]
If you feel some documentation is missing then raise an issue requesting that documentation is missing. That would be the way to get it onto a list of missing documentation.

We have no intentions to enable discussion here, because if there is something that needs fixing an issue is the best place for it to be logged.

**Comment by calidion** [comment]
Ideas can get mature through discussion. 
And even if I think it is an issue, but you don't think it is.
It is a waste of time for me to create one.
As nowadays developers are getting more and more dictative,
normally creating a issue will get me a close and sometimes a blame as well.
