### ISSUE TITLE
Tables are hard to read in small viewport

### ISSUE THREAD

**Issue by tophf** [GoogleChrome/developer.chrome.com#38]
https://developer.chrome.com/docs/extensions/mv2/permission_warnings/

The current width is:
```css
.measure-long {
  max-width: 79ch;
}
```

It wastes 50% of available space and makes some of the content almost completely unreadable. The extension documentation has pages with very wide and deeply nested tables so the overall content width shouldn't be limited at all or it should be a much bigger value.

![image](https://user-images.githubusercontent.com/1310400/101589691-009f9e00-39fa-11eb-9dda-7ced33cf93ee.png)

**Comment by samthor** [comment]
Thanks for your feedback. Your solution could work on desktop but we have the same problem on small screened devices.

We're going to consider how we can potentially relayout this content where we have a small viewport to display it in.

**Comment by tophf** [comment]
FWIW, if the mobile devices constitute only a negligible portion of views you could go with this trivial solution of increasing the width first, then fix it properly in the future...

**Comment by robdodson** [comment]
I think there's an easy thing we can do to really improve this page. Our lists currently have left/right margins applied to them so they appear inset when they're inside body copy. But **we're not removing those margins when lists are inside of tables** so they're getting crushed.

Here's the above screenshot if we remove the margins.

![image](https://user-images.githubusercontent.com/1066253/105261187-084b7a00-5b44-11eb-858f-1b5b8c45d426.png)

I bet there's more we can do to improve the appearance of text inside of tables. I just did some fairly baseline styles for them but now that they have a lot of real and varied content, we can tweak things.

I don't think we should increase the overall line length of the page much (though we could bump it up a tad if folks want). But you don't want line lengths to run longer than around 60-80 chars because it becomes harder to read (the eyes struggle to read text on very long lines).

Wikipedia is a good example of a site that does this poorly. They don't constrain line lengths at all, so you end up with this:

![image](https://user-images.githubusercontent.com/1066253/105260849-60ce4780-5b43-11eb-8bb9-b5bde095f43f.png)

Compared to something like Medium which constrains the line length to something like the 60-75 char range and is easier to read.

![image](https://user-images.githubusercontent.com/1066253/105260942-92471300-5b43-11eb-9b7a-b4672b23525c.png)

**Comment by tophf** [comment]
Indeed, Wikipedia is unreadable without a custom userstyle, but the blog example is also not ideal as 79 characters is too little for *documentation*, which is not a short blog article, it's a technical reference with complex formatting.
