### ISSUE TITLE
New site is missing API version information

### ISSUE THREAD

**Issue by hanguokai** [GoogleChrome/developer.chrome.com#39]
I found there is no "Since Chrome _version_" in new api reference. In the past, there are many statement say like "Since Chrome 48". This information is useful for compatibility. Developers can detect features or set "minimum_chrome_version" in manifest.

**Comment by samthor** [comment]
Thanks for the bug report.

We found that the vast majority of API versions in the old site were set
incorrectly to 38 (everything without correct data was set to this). There
were a handful of more up to date APIs and we will be bringing version
information back for things introduced in the past couple of years (38
won't be included, as it was from 2014) once we can identify what was
recently changed, and we hope to have this information up in the coming
days.

**Comment by tophf** [comment]
> for things introduced in the past couple of years

There was just a handful of changes in the extensions API over the past couple of years so if that's your threshold we will lose all the info from the past ~8 years of development like the one below for [chrome.tabs API](https://developer.chrome.com/docs/extensions/reference/tabs/). It's understandable that Chromium/Google supports only the current stable version but this info is helpful for us extension authors as we often keep our extensions compatible with older versions of Chrome.

![pic](https://user-images.githubusercontent.com/1310400/101986078-cb66aa80-3c9c-11eb-9012-3ddb8aaca661.png)

**Comment by dotproto** [comment]
I took the liberty of updating the issue title to reflect the observed bug rather than describing a feature request.

**Comment by hanguokai** [comment]
I hope this issue can increase the priority, because it affects the experience to all developers.

**Comment by tconfrey** [comment]
Adding my two cents. In my experience this is more serious than just 'Since' or 'Deprecated' for specific arguments or methods. 

The main [API Reference page](https://developer.chrome.com/docs/extensions/reference/) lists 'Stable' APIs while also having Beta and Dev sections. 'tabGroups' is shown under Stable and nowhere else, but I have found that that whole API is not available on the Stable channel. Similarly the 'group' method on 'tabs' is not available on Stable. 

This is a pretty big gap between advertised and available functionality! The site is not just missing api version information it's explicitly giving the wrong information.

How can I find out when tabGroups will be available via API?

**Comment by samthor** [comment]
Please take a look at #364 if you're curious about how we're going for a fix.

https://deploy-preview-364--developer-chrome-com.netlify.app/ is its staging URL.
