### ISSUE TITLE
Broken Links and outdated information in Extension FAQ

### ISSUE THREAD

**Issue by TravisBumgarner** [GoogleChrome/developer.chrome.com#3905]
**Describe the bug**
https://developer.chrome.com/docs/extensions/mv3/faq/
> Can extensions store data locally?
> Yes, extensions can use [localStorage](https://dev.w3.org/html5/webstorage/) to store string data permanently. Using Chrome's built-in JSON functions, you can store complex data structures in localStorage. For extensions that need to execute SQL queries on their stored data, Chrome implements [client side SQL databases](https://dev.w3.org/html5/webdatabase/), which may be used as well.

Looks like WebSQL is on the way out too: https://developer.chrome.com/blog/deprecating-web-sql/

**Comment by Arun7897kumar** [comment]
https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use httpitself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
A clear and concise description of what the bug is.
s://crbug.com.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by dstmarthe** [comment]
Thanks for raising this. Closing as it looks to have been re-worded. https://developer.chrome.com/docs/extensions/mv3/faq/#faq-dev-08
