### ISSUE TITLE
Invalid Information at developer.chrome.com/docs/extensions/mv3/background_migration

### ISSUE THREAD

**Issue by TheColaber** [GoogleChrome/developer.chrome.com#398]
**Describe the bug**
I wanted to migrate my extension from v2 to v3 and it has a background page. On the docs, it says 
![image](https://user-images.githubusercontent.com/72760579/107457626-673b5800-6b20-11eb-938e-f8eeaeac1dec.png)

When using `scripts`, `persistent` and `page`, I get an error like this: 
![image](https://user-images.githubusercontent.com/72760579/107457758-a8cc0300-6b20-11eb-9263-33a164430794.png)

Source: https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/mv3/background_migration/index.md

**To Reproduce**
1. Make an extension and have a background page.
2. Try using `scripts`, `persistent` or `page`. 
3. See error

**Expected behavior**
Correct information so I can actually make my extension work.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 88.0.4324.96 (Official Build) (64-bit)

**Comment by dotproto** [comment]
Since this issue was reported we merged [PR 387](https://github.com/GoogleChrome/developer.chrome.com/pull/387), which removed [mv3/background_migration](https://developer.chrome.com/docs/extensions/mv3/background_migration) and replaced it with [mv3/migrating_to_service_workers/](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/).
