### ISSUE TITLE
Rethink/rewrite: Overview/what are extensions page

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#401]
This page needs cleanup. At a minimum, remove the "Featured videos" section that points to videos 10+ years old.

**Comment by rdcronin** [comment]
Yay!

A few other quick asks:
- update screenshots (similarly old ; ))
- Don't reference the GMail Checker Extension, since it links to a page that links to a github repo that has out of date samples
- Update "overriding an entire page" reference to point to something a bit more canonically "extension-y"
- Update link to chrome dev dashboard (I think it still points to the old one, though it will auto-redirect)
- Update references to where resources can be downloaded

FWIW, many of the videos are actually still valuable - e.g. content scripts, isolated worlds.  I'd like to make sure we still point to them _somewhere_ (perhaps just within the relevant articles), but agree they shouldn't be as front-and-center as they are now.
