### ISSUE TITLE
Request manifest 3 demo and oauth2 credentials

### ISSUE THREAD

**Issue by ohowlett** [GoogleChrome/developer.chrome.com#4026]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dstmarthe** [comment]
Hi, this repo is specifically for d.c.c content issues. I'm not sure exactly what this issue is asking, but if you're requesting a demo of these functionalities I suggest opening an issue in our [new issue tracker](https://issuetracker.google.com/issues?q=status:open%20componentid:1400036&s=created_time:desc) with more informations on what you're looking for.
