### ISSUE TITLE
https://developer.chrome.com/docs/extensions/apps/ broken hyperlink in new version of ChromeApps

### ISSUE THREAD

**Issue by sfxcwys** [GoogleChrome/developer.chrome.com#4083]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
Hyperlink at "new version of Chrome Apps" is broken

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/apps/
2. Click on 'the hyperlink at 'Chrome Apps'
![Screen Shot 2022-10-21 at 4 56 16 PM](https://user-images.githubusercontent.com/7331852/197287554-221e4644-174a-441e-97ec-990978d50e38.png)
3. Got redirected to the error page https://developer.chrome.com/docs/apps/about_apps/
![Screen Shot 2022-10-21 at 4 57 54 PM](https://user-images.githubusercontent.com/7331852/197287541-2222e91e-cd4a-4d3a-8794-286b4f43e2b7.png)

**Expected behavior**
Should not see an error page.

**Screenshots**
- Click on 'the hyperlink at 'Chrome Apps' returns an error page
![Screen Shot 2022-10-21 at 4 56 16 PM](https://user-images.githubusercontent.com/7331852/197287554-221e4644-174a-441e-97ec-990978d50e38.png)

- Error page returned
![Screen Shot 2022-10-21 at 4 57 54 PM](https://user-images.githubusercontent.com/7331852/197287541-2222e91e-cd4a-4d3a-8794-286b4f43e2b7.png)

**Comment by jpmedley** [comment]
@sfxcwys,

Thank you for bringing this to my attention. I'm new to extensions, and still playing catch up. Apps of any kind, packaged or otherwise, are no longer supported except on Chrome OS. We'll likely remove this page altogether. 

Are you trying to solve a particular problem, or did you just stumble on this page by accident. 

(Here's some information on [converting to extensions](https://developer.chrome.com/docs/apps/migration/) if you need it.)
