### ISSUE TITLE
Documentation not getting me there. Help?

### ISSUE THREAD

**Issue by jrichview** [GoogleChrome/developer.chrome.com#4358]
I have an idea for a plugin. I have the JS/HTML/CSS skills.  I've read through the docs and looked at a few examples, but I am a bit confused how to access.  I'm trying to create a plugin that does the following:

1) Loads only on a certain webpage (done!)
2) Parses content from another related page on the same domain as well as the main page's content, then creates an array of data which is intended to be displayed in a table (done!)
3) Pops up a small window to display that table of data  (almost working!)

I'm pretty close to having this working. I have a JS file that runs when the main webpage is loaded. Did it using content_scripts in the manifest:

```
    "content_scripts": [
        {
          "js": ["mypage.js"],
          "matches": [
            "https://mainpageurlhere/*"
          ]
        }
      ],
```

The script successfully does the parsing of data from the 2nd HTML page as well as the main page and composes the array correctly. I have used the "action" and "default_popup" to display my popup over the main page and to layout the HTML table. 

Two things I haven't figured out yet:
(1)  when the icon is clicked and the popup is displayed, it needs to display the data from the array in the table. Two problems with this: 
      (A) The script loaded by the popup page's html needs to find the HTML table, but the DOM it is parsing is NOT the popup's DOM for some reason, it is the main page's DOM for some reason???  
      (B) Can the script loaded on the popup page somehow access the array that was declared and populated within the content script???
(2) I'd like to hook the CHANGE event on the main page on a <UL> and when any of the <LI> content in the UL changes, I'd like to trigger a script to re-compare the updated main page's data with the other page's data and re-display the table content.

**Comment by AaronForinton** [comment]
Hello and thanks for submitting your issue! 

I'm going to recommend your engage with the folks over at [https://groups.google.com/a/chromium.org/g/chromium-extensions](https://groups.google.com/a/chromium.org/g/chromium-extensions) in order to get some clarity on these issues. If you submit your questions there, someone with the Extensions knowhow will get back to you. 

I'll be closing this ticket now as we use this board primarily for documentation deployment bugs and content. I hope everything goes well with your plugin!
