### ISSUE TITLE
Chrome doesn't save my password

### ISSUE THREAD

**Issue by ColleenKuang** [GoogleChrome/developer.chrome.com#4373]
I have encountered this problem since I updated the newest version of Chrome. 
Everytime I open Chrome and import the saved passwords from csv file, and then when I reopen Chrome, the password which imported from the last time will disappear. 

Here's the method I tried:
1. Reinstall Chrome
2. Install Chrome on Drive `D:`
3. Manually save password (I try this method one time with My GitHub Account)

The mentioned methods don't work.

**Desktop:**
 - OS: Windows 64 21H2
 - Browser: Chrome
 - Version:107.0.5304.107 (Official Build) (64-bit)

**ScreenShots**
Before closing
![The imported result](https://user-images.githubusercontent.com/13173313/203547544-68c30489-6550-4eb7-beb6-ed1f17fd1d1b.png)

![My setting](https://user-images.githubusercontent.com/13173313/203547672-7630ebb4-9b89-4be2-867e-f2b51ca59046.png)

![The screen shot from Google Accont Security](https://user-images.githubusercontent.com/13173313/203547839-7120e6a7-fc68-434d-90f0-7d065390f826.png)

* Reopening

![The screen shot from Google Accont Security](https://user-images.githubusercontent.com/13173313/203548255-93610c4d-8804-47b8-9a52-fd4ee9f95e52.png)

![The screen shot from Chrome Password Manager](https://user-images.githubusercontent.com/13173313/203548270-1bc40a17-461e-40fe-9291-05365a034b39.png)

PS: Chrome works fine on my mobile, but not on desktop version

**Comment by AaronForinton** [comment]
Hello! Since this isn't a bug related to [developer.chrome.com](https://developer.chrome.com) but is instead an issue with the Chrome Browser, I'm going to be closing this issue.

I'd like to recommend you reporting this issue in browser [(instructions here)](https://support.google.com/chrome/answer/95315). You can also file a new issue with the [Chromium Developers](https://bugs.chromium.org/p/chromium/issues/entry).
