### ISSUE TITLE
[Question] Can chrome-extesnion work differently for different systems ? (Ex. apple silicon Mac and Intel Mac)

### ISSUE THREAD

**Issue by PENEKhun** [GoogleChrome/developer.chrome.com#4391]
Hello, best developers in the world!
I am a college student studying development in Korea.

Some of my clients are claiming that the chrome-extesion I provided works on Intel Macs but not on Silicon Macs. But I don't understand this. It was because there was no such issue in the v8 engine.
I would like to ask a question related to this, but there is no way, so I asked it on a github issue.

Assuming the chrome version is the same,
Excluding external factors such as thrid-party API integration not related to Chrome,
Can chrome-extesnion work differently for different systems (or architectures)?

For example,
In the same chrome extension source code, it works on Intel Mac, but does not work on Apple silicon MacBook.

Thanks in advance for your reply.
I wish all the developers involved, including those who read this article, a good end of the year.

**Comment by Anuragkillswitch** [comment]
@PENEKhun extension*

**Comment by AaronForinton** [comment]
Hi there @PENEKhun and thanks for dropping in with your question. Since we use this board primarily for documentation-related issues, I'm going to be closing this issue. I'd recommend you ask this either at:

- The [extensions forum](https://groups.google.com/a/chromium.org/g/chromium-extensions). 
- [Stack Overflow](https://stackoverflow.com/questions/tagged/google-chrome-extension).

Thank you, and wishing you a good end of year right back. :)
