### ISSUE TITLE
Can't subscribe to blog via rss

### ISSUE THREAD

**Issue by hd321kbps** [GoogleChrome/developer.chrome.com#4472]
Hello!
I have such a problem.
I want to subscribe to the blog
https://developer.chrome.com/feeds/blog.xml
by RSS.
I use the Feedbro browser extension.
For some reason, the channel is not available and gives a 403 error.
Can this be solved somehow?

**Comment by nodeticswww** [comment]
One problem with the server is that it always sends this HTTP Response header:

last-modified: Tue, 01 Jan 1980 00:00:01 GMT

Feedbro uses HTTP conditional gets by sending "If-Modified-Since" header which causes the server to respond with 304 Not Modified -> feed cannot be loaded.

**Comment by hd321kbps** [comment]
> One problem with the server is that it always sends this HTTP Response header:
> 
> last-modified: Tue, 01 Jan 1980 00:00:01 GMT
> 
> Feedbro uses HTTP conditional gets by sending "If-Modified-Since" header which causes the server to respond with 304 Not Modified -> feed cannot be loaded.

It's not entirely clear how to solve the problem.
I wrote to the FeedBro team. They said that the problem is on the side of the Google Chrome servers and they cannot influence it.

**Comment by BrandonML** [comment]
I also found this issue when trying to subscribe using FeedBro. I get a 304 response when trying to subscribe to the feed the OP mentioned, as well as "What's New" in DevTools: https://developer.chrome.com/feeds/new-in-devtools.xml .

**Comment by Jxck** [comment]
same things happens here too.

https://developers.google.com/web/updates/rss.xml

**Comment by MichaelSolati** [comment]
@devnook I built the feeds on DCC (I think), I can definitely take a look at this and fix the feeds if you'd like.

**Comment by MichaelSolati** [comment]
@Jxck, the feed for developers.google.com is handled via a different project/team than developer.chrome.com. Someone here can probably escalate the issue, but it won't be resolved by any fix applied here.

@hd321kbps I'm assuming you meant 304.

And for @devnook not just the RSS feeds are returning 304s, but also the home page. Though this is in Chrome, if you curl the URLs you get a 200, but the last modified date is in 1980.

![image](https://user-images.githubusercontent.com/11811422/212735215-9063d534-2c92-4dcc-a063-24b0d05783fa.png)

![image](https://user-images.githubusercontent.com/11811422/212735311-b532f3a0-aeac-46fc-a8b1-acdf28d52dd5.png)

**Comment by MichaelSolati** [comment]
Second update, when running the dev server, or building the prod version of the app, the home page returns 200 and RSS feeds return 304. However, there is no issue loading the RSS feed in Feedbro.

RSS feeds have the correct "last modified" date.

---

The only real difference I'm finding between them is the HTTP protocol they're being served over. Localhost is served over http/1.1 where as the deployed environment is served over h3 (http/3). That shouldn't make a difference though, web.dev uses http/3.

So what's the conclusion, no idea.

Other RSS/feed apps read it just fine, such as feedly, feeder, and inoreader.

[W3C feed validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdeveloper.chrome.com%2Ffeeds%2Fblog.xml) can read the feed and says it's a-ok!

Feedbro has a "feature" that ignores RSS feeds that haven't been updated in x number of days, and the maximum number of days you can set is like 730. I'm wondering if it's taking that "last modified" being returned in the headers and ignoring the feed as a result. Like the feed is valid, other apps can read the feed, so that's the only thing I can think of.

And now I'm off, having provided no solutions and only finding more mysteries. Hopefully, it was helpful; I wanted to actually provide code, but this is the best I can discover. Sorry I couldn't do more.

**Comment by hd321kbps** [comment]
> I'm assuming you meant 304.
Yes, exactly.

**Comment by nodeticswww** [comment]
The fix is simple. The server should return a valid "Last-Modified" header that reflects the _actual_ date when the feed was last modified OR remove that header completely.

But since the server sends that completely false header "last-modified: Tue, 01 Jan 1980 00:00:01 GMT" and Feedbro uses HTTP conditional GETs using (If-Modified-Since) (sending the date of the latest scanned article), the server responds with 304 Not Modified and doesn't send any data.

Thus all subsequent scans to the feed fail.

**Comment by matthiasrohmer** [comment]
Setting a correct `last-modified` header unfortunately is not possible with the current setup. As App Engine zeros the timestamps on files, also see https://issuetracker.google.com/issues/168399701.

We are currently working on a different serving method which will enable correct headers though.

**Comment by simevidas** [comment]
I am unable to add the following feed to Feedbro

https://developer.chrome.com/feeds/all.xml

https://user-images.githubusercontent.com/716405/236623091-abc7ac31-1df8-4c42-b01a-73cdd657cd0b.mp4

**Comment by simevidas** [comment]
When I inspect the HTTP request that Feedbro is making and the response from Google’s server, I see no `last-modified`. Instead, the caching seems to be based on `if-none-match` and `etag`.

When I edit the request to remove the `if-none-match` header and re-send the request, I get a 200 response with the feed content.

<img width="1280" alt="Screenshot 2023-05-06 at 14 42 05" src="https://user-images.githubusercontent.com/716405/236624975-f38a73e0-bbdb-4ab0-bc04-7b32df78d1ba.png">

**Comment by matthiasrohmer** [comment]
Won't fix, due to the pending move to the new CMS.

**Comment by hd321kbps** [comment]
> Won't fix, due to the pending move to the new CMS.

when it will be?

**Comment by nodeticswww** [comment]
> When I inspect the HTTP request that Feedbro is making and the response from Google’s server, I see no `last-modified`. Instead, the caching seems to be based on `if-none-match` and `etag`.
> 
> When I edit the request to remove the `if-none-match` header and re-send the request, I get a 200 response with the feed content.
> 
> <img alt="Screenshot 2023-05-06 at 14 42 05" width="1280" src="https://user-images.githubusercontent.com/716405/236624975-f38a73e0-bbdb-4ab0-bc04-7b32df78d1ba.png">

Looks like the bug is then actually with the "If-None-Match" header handling. Etag should change if the content changes but apparently it doesn't change. Then the server responds with 304 (not modified) when HTTP GET is done with "If-None-Match" header.
