### ISSUE TITLE
Offscreen Documents

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4476]
Content to be determined.

**Comment by guest271314** [comment]
@IanStanion-google Can you kindly have a look at https://github.com/GoogleChrome/developer.chrome.com/issues/4200. The functionality of `setSelfAsOpener` cannot be used in MV3. 

It makes sense to continue that functionality in MV3 with `CreateParameters` passed to `offscreen.createDocument()`, so developers can set arbitrary Web pages as `opener` to facilitate using Transferable objects with `opener.postMessage(data, [data.buffer /* readable, writable */])`. 

Currently we have to use an `iframe` which is not ideal because for some developers the concern is the `iframe` can be removed by other code; or `open()`, where the `window` cannot be immediately set to non-visible, and is always at least 100x100 initially.

**Comment by AmySteam** [comment]
Related PR #4765
