### ISSUE TITLE
Write support information pages for Extensions and Web Store Docs

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/developer.chrome.com#4786]
We currently have nothing on our websites that tell users where to go for help.

**Comment by 3kunuk** [comment]
if my chromebook has developer mode and settings, what does this mean? Somehow my iphone which I suspect is not even an iphone is linked to my chromebook. What is the point to all of the above. Why the code talk? Why are things impossible for me to understand? Why the mis-spelled words and crap? Can someone please help me?? PLease. When I called apple which I have done like 40 times, noone will actually help me. I've lost $220 to apple "iTunes" due to the media terms and conditions apparently and $502 to Strip b/c of phone/chromebook being in developer mode which I have no idea what that is or how it happened. Other than if it was my ex husband, my mother, or ex boyfriend. Or maybe my son. Or hell, perhaps its all of them lol
