### ISSUE TITLE
Describe the values of chrome.offscreen.Reason 

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#4788]
**Describe the bug**
The Offscreen API reference page does not provide sufficient information for extension developers to understand how and why they might use a given Reason value.

**Expected behavior**
Either the [Reason enum's documentation](https://developer.chrome.com/docs/extensions/reference/offscreen/#type-Reason) or the intro text on the page should describe the intended use of each reason.

**Additional context**
[Relevant thread](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/6-yk7QdGtOo/) on the chromium-extensions group.

**Comment by robbi73** [comment]
Hi, I would like to have some clarification on some aspects of this new API.

1) What could happen by improperly specifying the "reasons" property?
    a) The rejection of the review process?
    b) The closing\"not opening" of offscreen document whenever there is no correlation between the stated "reason" and the used code?
	
2) Can we use the same offscreen document for several "reasons"?
In an extensions of mine I'm using the same html+js for "AUDIO_PLAYBACK", "DOM_PARSER" (I also use that OSD to manage a web worker).
Could this choice be considered imprudent/questionable?

3) To display an "alert" or a "confirm" (or in general a method of the window object) can the "DOM_PARSER" reason be fine?

Considerations:
It would be nice to have some reassurance today about how "justification" and "reasons" will be used in order to not have surprises later when our extensions will be published.

Thank you.

comment [69](https://bugs.chromium.org/p/chromium/issues/detail?id=1339382#c68) at  https://bugs.chromium.org

**Comment by guest271314** [comment]
Or, remove the "justification" and "reasons" properties altogether, as they are, AFAICT, _hints_ that do not restrict code that neither of the values listed for either.

**Comment by AmySteam** [comment]
Fixed in #6201
