### ISSUE TITLE
A standard way to indicate a blog post is outdated and link to the new material

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/developer.chrome.com#4830]
Now that we have a documentation project ongoing, I'm going to be a bit more active in chasing docs out of the blog in preference for blog posts being news (ref: [where to publish](https://developer.chrome.com/docs/handbook/where-to-publish/)). As they are news, what we want to avoid is people going back and making major edits to an old post due to the API changing. This rewrites history, means that people can't track the evolution of ideas, and is just confusing.

That said, we do want to avoid people stumbling across old blog posts and thinking they are current, so I'd like to have some kind of standard callout for the top of posts that we can add without fundamentally changing the content of the post, but that clearly highlights that this is historical info, and points to new material (new blog posts, the MDN docs etc.)

**Comment by agektmr** [comment]
Can we stick the banner at the top or the bottom of the page so that the warning is visible anywhere in the page?

**Comment by guest271314** [comment]
The Native Messaging page is very outdated. The linked sample still uses Python 2 which is deprecated. Along with `setSelfAsOpener` in `chrome.windows`

**Comment by guest271314** [comment]
> but that clearly highlights that this is historical info, and points to new material (new blog posts, the MDN docs etc.)

You can't assume or rely on MDN to be up to date either. MDN's Native Messaging example uses `python` in the shebang, which on many Linux systems does not exist - `python3` needs to be used. Further the MDN Python Native Messaging host does not process 1MB of input from user correctly because `json.demps()` inserts space characters which are counted as message length, not so easy to discover unless you are actually testing 1MB input to Native Messaging host, which evidently nobody in developer.chrome nor MDN has done. 

- https://github.com/mdn/webextensions-examples/issues/509
- https://github.com/GoogleChrome/chrome-extensions-samples/issues/805

**Comment by guest271314** [comment]
The only way to do this effectively is to review and test the claims and code in **all** of the pages on developer.chrome.com/. Then be donw with the matter. Else this will be strung out for years, awaiting somebody to locate old news and post it here.

**Comment by devnook** [comment]
Design is locked in, please continue with dev work.

**Comment by tokyodanj** [comment]
**Note for dev team when picking this up:**

The **red-darkest** color var has been darkened slightly to achieve AAA contrast (#a50e0e > #9f0e0e). That change will need to be applied globally.
