### ISSUE TITLE
[manifest v3] Debugging background service worker "service worker registration failed"

### ISSUE THREAD

**Issue by SaudTauqeer** [GoogleChrome/developer.chrome.com#487]
**Is your feature request related to a problem? Please describe.**
I have been migrating a fairly large codebase from manifest `v2` -> `v3`. The problem I'm facing is that all errors within the `background.js` service worker script give a generic "service worker registration failed". Since you can't inspect the script without having the service worker actually running, this makes debugging hard.

**Describe the solution you'd like**
- ability to see why the "service worker registration failed" or more specifically what went wrong in the background service worker script?

**Describe alternatives you've considered**
- I understand that v3 is fairly new so this is the only relevant thing i was able to try out which didn't work out for me: https://stackoverflow.com/a/66437283

**Additional context**
n/a

**Comment by dotproto** [comment]
This issue is being tracked on the Chromium tracker at https://bugs.chromium.org/p/chromium/issues/detail?id=1152202. Please be aware that repository is only for Chrome Extensions and Chrome Apps examples.

There are a couple ways to work around this, but my current prefered solution is to proxy my background script in a simple try/catch block that logs the error to the console. I explain it in detail in [this post on chromium-extensions](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/lLb3EJzjw0o/m/cBuC_OJ7AQAJ).
