### ISSUE TITLE
Events widget for reuse in Privacy Sandbox

### ISSUE THREAD

**Issue by nancymic2** [GoogleChrome/developer.chrome.com#5333]
We need a version of the meet the team page in chrome developers to be used in Privacy sandbox docs. It cannot just be copied because https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_collections/events.js#:~:text=.getFilteredByGlob(%60./site/%24%7Blocale%7D/meet%2Dthe%2Dteam/events/**/*.md%60) looks only in the chrome meet the team folders for events. It would be good if there was a way to have it look in some place (like privacy sandbox events )when using it there. It would not share content though. The privacy sandbox will have separate events. 

**Describe the solution you'd like**
The same format of page with the same functionality as https://developer.chrome.com/meet-the-team/ but in privacy sandbox. I.e. that the code is reusable.

**Describe alternatives you've considered**
Copying all the files is how we discovered that the content is only pulled from chrome meet the team

**Comment by rachelandrew** [comment]
I'm not sure this is a great idea. I think if we want to be able to show a subset of events then, rather than copying the page, we should consider how we can better filter the events that are listed. That way this becomes a reusable feature.

For example, I could imagine having a widget that allowed you to pull back a filtered list of events.

There would be a bunch of work to duplicate the page, which would the need redoing everytime anything changed. If we create something reusable, then it is there for any team to take advantage of and we don't add a maintenance overhead for each instance of it.

**Comment by heyawhite** [comment]
I renamed the issue and want to propose yes, we would like to show a subset of events in the same style as the current events page. It would be great to have a widget which offers a filter of events from Chrome Meet the Team which means there's just one input for our team but multiple possible outputs.

The most reusable and moldable method possible.

**Comment by heyawhite** [comment]
We've also received requests from our Partnerships team to include a calendar with W3C calls. Re-raising interest in this request.

**Comment by heyawhite** [comment]
Closing this out.
