### ISSUE TITLE
Broken Link on MV3 Manifest Info Page

### ISSUE THREAD

**Issue by f-eli-pe** [GoogleChrome/developer.chrome.com#5409]
**Bug Description**
Broken link on MV3 Manifest File Format Page. https://developer.chrome.com/docs/extensions/mv3/manifest/.

When clicking on the replacement_web_app link, https://developer.chrome.com/docs/extensions/mv3/manifest/replacement_web_app/ it leads to a 404. 

I opened a PR that fixes this. https://github.com/GoogleChrome/developer.chrome.com/pull/5389

**Comment by AmySteam** [comment]
@f-eli-pe Thanks for pointing this out and making a PR 🙂.

The way to fix this, however, will be to remove the key from the manifest list. Since Chrome Apps are deprecated, we only want to keep the keys supported by extensions on this page.

@f-eli-pe Would you be interested in opening a PR to remove the `replacement_web_app` key from the list?

❌  <span class="token property">"<a href="/docs/extensions/mv3/manifest/replacement_web_app">replacement_web_app</a>"</span><span class="token operator">:</span> <span class="token string">"https://example.com"</span><span class="token punctuation">,</span>

**Comment by f-eli-pe** [comment]
@AmySteam Sure! I'll do this later today 🙂
