### ISSUE TITLE
File input field does not always work on all websites

### ISSUE THREAD

**Issue by bhargavraviya** [GoogleChrome/developer.chrome.com#5528]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
The Chrome file input field does not always work on all websites. After closing the Chrome browser, it worked properly.

**Expected behavior**
working file input field properly on all websites

**Desktop (please complete the following information):**
 - OS: [macOS 12.1 (21C52)]
 - Browser [Chrome ]
 - Version [110.0.5481.177 (Official Build) (arm64)]

**Comment by AaronForinton** [comment]
Hi there @bhargavraviya and thanks for submitting your issue. Since this is an issue with Chrome browser rather than our documentation at developer.chrome.com, I'm going to close this issue and request you submit your problem using the instructions [provided here](https://support.google.com/chrome/answer/95315). Thank you.
