### ISSUE TITLE
In live-headers demo, chrome.runtime.lastError always no null

### ISSUE THREAD

**Issue by snowman** [GoogleChrome/developer.chrome.com#5617]
https://github.com/GoogleChrome/chrome-extensions-samples/blob/a0f47934ea5cc950a745b803d0d2a515a26ab43d/mv2-archive/api/debugger/live-headers/background.js#L12-L16

it shows `error:  Cannot access a chrome-extension:// URL of different extension`, although I am *NOT* click the extension icon in `chrome://*` or `chrome-extension://` page, this even happens in `google.com`

**Comment by patrickkettner** [comment]
hi @snowman - thanks a ton for your patience here. I am not able to replicate the problem, and given that it goes away when you use a fresh profile and the simplicity of the live headers extension, it sounds like a race condition. If you can 100% of the time replicate it on your normal profile, would you be able to list the extensions you have installed? I'd love to see if I am able to replicate with a similar setup.

**Comment by dstmarthe** [comment]
Hi @snowman thanks for raising this issue. We've moved to a new issue tracking platform. Since it's been a while, and with Patrick's answer, I'm going to close this. But you can always open an issue on the new tracker if you would like further advice. See: https://issuetracker.google.com/issues/new?component=1400036&template=1897236
