### ISSUE TITLE
Context menu in Application/Storage not working anymore

### ISSUE THREAD

**Issue by jsbrain** [GoogleChrome/developer.chrome.com#5715]
**Describe the bug**

When selecting a key-value pair from Local Storage so the value shows up in the lower pane, I used to right click to open the context menu and copy values from e.g. json value.

This is not working anymore, I think it's since I updated to the latest version.

**To Reproduce**
1. Open Dev Tools
2. Go to Application tab
3. Click on Local Storage
4. Select any key-value pair
5. Try open the context menu via right click (works on the upper pane, but not the lower where the value is shown)

**Expected behavior**
Open the context menu on right click.

**Screenshots**
This is how it used to work (screenshot from Edge)
<img width="666" alt="Screen Shot 2023-03-17 at 08 20 07" src="https://user-images.githubusercontent.com/20225909/225839853-4da68df7-0691-4381-814a-612d82c2027b.png">

**Desktop:**
 - OS: macOS
 - Browser chrome
 - Version 111.0.5563.64

**Comment by AaronForinton** [comment]
Hi there @jsbrain and thanks for submitting your issue. Since this is a documentation repo rather than an engineering one, I'm going to close this issue - but I'd like to direct you to the appropriate area of the [crbug.com](https://bugs.chromium.org/p/chromium/issues/list?q=component:Platform%3EDevTools) so you can report this issue to the DevTools engineering team. Thank you.
