### ISSUE TITLE
Add private permissions to the documentation

### ISSUE THREAD

**Issue by Lars418** [GoogleChrome/developer.chrome.com#638]
**Is your feature request related to a problem? Please describe.**
The current documentation for chrome extensions does not include any information about the private apis that Chrome/Google is using in some of their own extensions/apps. An example would be the "developerPrivate" api. The permissions are only granted for some specific apps and it is also not possible to upload an extension using one of these private apis, but it would nontheless be a nice addition for enterprise/personal extensions.

**Describe the solution you'd like**
Add the private apis/permissions to the developer.chrome.com documentation (and maybe even some examples to the Github repo).

**Describe alternatives you've considered**
[This file](https://chromium.googlesource.com/chromium/chromium/+/74487698cb9d0473dcc487b022c360f75cadb32b/chrome/common/extensions/api/_permission_features.json) seems includes a list of all availiable permissions/apis.

**Additional context**

**Comment by rdcronin** [comment]
Thank you for the feature request!  Unfortunately, I don't think this is something we want to do.

Private APIs are designed for use primarily by features of Chromium - the fact that they are an extension API is, more than anything else, an implementation detail (you can see a bit more detail on this here [1]).  For instance, the developerPrivate API is used by the chrome://extensions page to facilitate loading and managing extensions.  These APIs aren't meant for any kind of public consumption - they are restricted in their use, and are also not designed to be stable at all.  They are frequently changed often without any warning, and are also more powerful than we would allow other extensions to use.  We think that documenting them on developer.chrome.com/extensions would send the wrong message - implying they are both more stable and more publicly-usable than they are.

Since these are largely designed for use only by features of Chromium, I think it makes sense that they continue to only be documented in the Chromium codebase (which, of course, is open source).

In line with this, I'm going to go ahead and close this out, but thank you again for bringing it up!

[1] https://chromium.googlesource.com/chromium/src/+/HEAD/extensions/docs/new_api_proposal.md#public-or-private
