### ISSUE TITLE
Create non active tab while dragging another tab

### ISSUE THREAD

**Issue by adlerfaulkner** [GoogleChrome/developer.chrome.com#652]
**Describe the bug**
If a non active tab is created via `chrome.tabs.create({ ... , active: false })` in the newly created window that another tab is being dragged into, the drag is canceled and the dragged tab goes back to it's original window.

**To Reproduce**
1. Clone the repo at [https://github.com/adlerfaulkner/chrome-tab-drag-bug](https://github.com/adlerfaulkner/chrome-tab-drag-bug)
2. Turn off any other extensions running in chrome
3. Drag the repo folder into [chrome://extensions](chrome://extensions)
4. Start with a single window that has one or more tabs
5. Try to drag a tab to a new window
6. You can increase the timeout in `background.js` to see the effect happen after you've dragged a bit further than I did in my video.

**Expected behavior**
The tab created via `chrome.tabs.create({ ... , active: false })` should be created in the new window and the dragged tab should remain in the dragged state until it is dropped. It should not revert back to its original position in the old window.

**Screenshots**
https://user-images.githubusercontent.com/8572428/114949291-8ea2ef80-9e05-11eb-888e-c595cfd942c7.mov

**Desktop**
 - OS: macOS Big Sur 11.2.3
 - Browser: Chrome & Edge
 - Version: 89.0.4389.114 (Official Build) (x86_64)

**Comment by dstmarthe** [comment]
Hi, thanks for raising this. We're in the process of migrating to a new platform, and I am closing issues on this tracker. Since this repo is for d.c.c content issues specifically, I have to close this topic. If you still need help with this here are two chromium resources:  
https://groups.google.com/a/chromium.org/g/chromium-extensions
https://bugs.chromium.org/p/chromium/issues/list
