### ISSUE TITLE
tabs.query not requiring tabs permission for using url property if host permission granted

### ISSUE THREAD

**Issue by camlani** [GoogleChrome/developer.chrome.com#655]
**Describe the bug**
Within Chrome API Tabs reference documentation: https://developer.chrome.com/docs/extensions/reference/tabs/, it appears that the language is inconsistent with the implementation.

Under tabs.query, within the queryInfo object for the url property the following is mentioned:

 `Match tabs against one or more URL patterns. Fragment identifiers are not matched. This property is ignored if the extension does not have the "tabs" permission.`

I was able to create a simple test extension which has the host permission for a site it should operate on, then without requesting the tabs permission was able to use the tabs.query permission. Thus the property is not ignored, if the host permission is granted in the extension.

The tabs permission seems only to be required if the extension does not have a host permission match for the site.

**To Reproduce**
1. Create test extension, with the only permission access to a host permission on a specific site.
2. Navigate to the site in question, invoke tabs.query with a url property in the queryInfo.
3. The tabs.query should return the callback properly.

**Expected behavior**
The documentation insinuates that the only way to use the url property of tabs.query queryInfo, is to request the tabs permission, which does not seem to be the case.

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Version: 89

**Comment by samthor** [comment]
My understanding of this is:

1. If you specify `"host_permissions"` (i.e., specific URL matches), you can use `chrome.tabs` to query/interact with matching tabs
2. Otherwise, you have to specify the "tabs" permission, which is a broader catch-all for tab management.

It seems as if the documentation has been written to focus on the 2nd point, but the 1st point is sort of a fallback. I'm happy not to change the documentation enormously—and still refer to the "tabs" permission in abstract—but I could see a section at the top of this page mention that `"host_permissions"` implicitly provide "tabs" over those matched tabs, being helpful and informative.

WDYT?

**Comment by dotproto** [comment]
@camlan, you're absolutely correct; both host permissions and the `tabs` permission will grant an extension the ability to read the sensitive properties on `tabs.Tab` instances, query those values in `tabs.query`, and otherwise leverage that data access. I didn't author this text, but I suspect that the original authors were trying to simplify the relationship between tabs and host permissions in order to make it a little easier for a casual reader to understand. 

@samthor, I agree that we should clarify the relationship between tabs and host permissions, and your suggested approach sounds like the most practical way to address the gap.

**Comment by AmySteam** [comment]
This concern was partially addressed in [PR#3102](https://github.com/GoogleChrome/developer.chrome.com/pull/3102), by adding a [Permissions](https://developer.chrome.com/docs/extensions/reference/tabs/#perms) section that describes the three permissions developers should be aware of when working with the Tabs API.

The next step is to update each individual property (such as the [title property](https://developer.chrome.com/docs/extensions/reference/tabs/#property-Tab-title)) to point to the Permissions section, instead of stating that the "tabs" permission is required.
