### ISSUE TITLE
Add a message passing example to the Tabs API's examples section

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#665]
I wanted to include a message passing demo on in the Tabs API's initial set of examples (#563), but I haven't had any particularly great ideas on what to demo. Suggestions welcome.

**Comment by tophf** [comment]
See if you like something in this list of most popular questions for chrome.tabs.sendMessage on StackOverflow: [link](https://stackoverflow.com/search?tab=votes&q=%5bgoogle-chrome-extension%5d%20chrome.tabs.sendmessage).

And here's an idea if you want to include something nontrivial: how to open a new tab and send a message to the content script of that tab. The problem is present both for manifest-declared scripts and executeScript-injected scripts: in both cases the callback of create() will be called too soon. There are at least two solutions: use chrome.tabs.onUpdated or let the content script initiate messaging.
