### ISSUE TITLE
Dev Tools closes unexpectedly after a minute or two of use

### ISSUE THREAD

**Issue by meitalvtn** [GoogleChrome/developer.chrome.com#7182]
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
NOTE: None of this happens on Chrome Beta!!!!! On Beta, everything works perfectly.

I have been using the dev tools for a while with no issues. However, recently after upgrading my Chrome to 116, the dev tools window works fine, but then closes unexpectedly after a few minutes (1-2) of use with no console errors.

When viewing the Chrome logs, I see these errors:

```
[40257:259:0827/134711.420939:ERROR:gles2_command_buffer_stub.cc(342)] ContextResult::kFatalFailure: Failed to create context.
[40258:12803:0827/134716.217207:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
[40258:12803:0827/134716.269515:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
[40258:12803:0827/134718.729766:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
[40258:12803:0827/134724.873269:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
[40258:12803:0827/134732.141752:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
[40258:12803:0827/134733.973121:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
[40257:259:0827/134800.515873:ERROR:gles2_command_buffer_stub.cc(342)] ContextResult::kFatalFailure: Failed to create context.
[40249:259:0827/134817.883576:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 18
[0827/134818.023883:WARNING:in_range_cast.h(38)] value -634136515 out of range
[40249:259:0827/134818.033895:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 18
```

When I open Chrome, I see the first `Failed to create context.` error.
Then, I see the handshake error,
Then, when the dev tools closes, I see the `Terminating renderer for bad IPC message` error.

**To Reproduce**
1. Go to any website, such as google.com.
2. Right click on "Inspect" to open dev tools.
3. After a few minutes, the window (whether docked in or out of the browser) closes unexpectedly.

**Expected behavior**
The dev tools continues to work.

**Desktop (please complete the following information):**
 - OS: Ventura 13.4 (M2 Macbook Pro)
 - Browser: Chrome
 - Version: 116.0.5845.110 (Official Build) (arm64)

**Additional context**
Please see the Chrome application logs I show above
More people seem to be having the same issue as shown in [this post](https://support.google.com/chrome/thread/231414792/devtools-automatically-closing?hl=en)

Other things I have tried:
- Uninstalling and re-installing Chrome
- Removing all browser extensions
- Turning off "hardware acceleration"
- Trying to use dev tools on a new profile
- See the console errors on dev tools

**Comment by GourishettySairam** [comment]
> ⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself. If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.
> 
> **Describe the bug** NOTE: None of this happens on Chrome Beta!!!!! On Beta, everything works perfectly.
> 
> I have been using the dev tools for a while with no issues. However, recently after upgrading my Chrome to 116, the dev tools window works fine, but then closes unexpectedly after a few minutes (1-2) of use with no console errors.
> 
> When viewing the Chrome logs, I see these errors:
> 
> ```
> [40257:259:0827/134711.420939:ERROR:gles2_command_buffer_stub.cc(342)] ContextResult::kFatalFailure: Failed to create context.
> [40258:12803:0827/134716.217207:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
> [40258:12803:0827/134716.269515:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
> [40258:12803:0827/134718.729766:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
> [40258:12803:0827/134724.873269:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
> [40258:12803:0827/134732.141752:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
> [40258:12803:0827/134733.973121:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; returned -1, SSL error code 1, net_error -101
> [40257:259:0827/134800.515873:ERROR:gles2_command_buffer_stub.cc(342)] ContextResult::kFatalFailure: Failed to create context.
> [40249:259:0827/134817.883576:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 18
> [0827/134818.023883:WARNING:in_range_cast.h(38)] value -634136515 out of range
> [40249:259:0827/134818.033895:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 18
> ```
> 
> When I open Chrome, I see the first `Failed to create context.` error. Then, I see the handshake error, Then, when the dev tools closes, I see the `Terminating renderer for bad IPC message` error.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to any website, such as google.com.
> 2. Right click on "Inspect" to open dev tools.
> 3. After a few minutes, the window (whether docked in or out of the browser) closes unexpectedly.
> 
> **Expected behavior** The dev tools continues to work.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ventura 13.4 (M2 Macbook Pro)
> * Browser: Chrome
> * Version: 116.0.5845.110 (Official Build) (arm64)
> 
> **Additional context** Please see the Chrome application logs I show above More people seem to be having the same issue as shown in [this post](https://support.google.com/chrome/thread/231414792/devtools-automatically-closing?hl=en)
> 
> Other things I have tried:
> 
> * Uninstalling and re-installing Chrome
> * Removing all browser extensions
> * Turning off "hardware acceleration"
> * Trying to use dev tools on a new profile
> * See the console errors on dev tools

Even I am facing the same issue, from the past 5 days
Exact same details as above
Any help is sincerely appreciated

**Comment by bw-79** [comment]
I have the same issue.

**Comment by vaditya92** [comment]
Facing the same issue since a week. Did anyone find a workaround?

**Comment by bw-79** [comment]
The issue for me was a folder with source files with a VERY large amount of images added to the sources panel of the devtools.

I removed all the sourcefolders in the preferences file of google chrome

AppData\Local\Google\Chrome\User Data\Default\Preferences

and the devtools started to function again as expected. Next I added an exception pattern in the workspaces options and now I'm able to work again.

Hope that helps someone.

**Comment by meitalvtn** [comment]
Another workaround for anyone who needs is to use chrome beta... The problem does not occur for me there

**Comment by bw-79** [comment]
I had exactly the same issue with the beta version after adding the same source code folder to the devtools workspace.

**Comment by vaditya92** [comment]
> Another workaround for anyone who needs is to use chrome beta... The problem does not occur for me there

I've been using the beta version too to get around this issue.

**Comment by neeeeecka** [comment]
Same on: Version 116.0.5845.140 (Official Build) (arm64)

**Comment by myakura** [comment]
Note that this repository isn't a bug forum for Chrome or Chromium browsers, but for the https://developer.chrome.com/ website.

There's already a bug filed against chromium issue tracker https://bugs.chromium.org/p/chromium/issues/detail?id=1473992 . It's not fixed yet, but you might want to check the issue instead of posting comments here.

**Comment by 0569395312** [comment]
Re: [GoogleChrome/developer.chrome.com] Dev Tools closes unexpectedly after  
a minute or two of use (Issue #7182)
الخميس 31 أغسطس 2023













احصل على Outlook for Android



من:‏ Masataka Yakura ***@***.***&gt;

تاريخ الإرسال: الخميس, أغسطس 31, 2023 12:14:41 م
إلى: GoogleChrome/developer.chrome.com  
***@***.***&gt;

نسخة: Subscribed ***@***.***&gt;
الموضوع:‏ Re: [GoogleChrome/developer.chrome.com] Dev Tools closes  
unexpectedly after a minute or two of use (Issue #7182)




Note that this repository isn't a bug forum for Chrome or Chromium  
browsers, but for the
https://developer.chrome.com/ website.
There's already a bug filed against chromium issue tracker
https://bugs.chromium.org/p/chromium/issues/detail?id=1473992 . It's not  
fixed yet, but you might want to check the issue instead of posting  
comments here.
—
Reply to this email directly,
view it on GitHub, or
unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID:
***@***.***&gt;





المنظم
***@***.***
***@***.***

المدعوّون
GoogleChrome/developer.chrome.com‏
GoogleChrome/developer.chrome.com‏
Subscribed‏ - اختياري
عرض جميع معلومات المدعوّ  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc2MHI0Y2c5aTYxMjNlaGEyOGgxNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNzRxMzRnaGw3NTEzMGNocDY4cDQ4ZGhrNzExNDhjcTU3MHA0OGQyNTZoMzMyZHExOGNxZyByZXBseStiYWZ3dXc0ZHVzdGRpd2xsNGN4b2s2NmM3d2dpZGV2Ym5oaGc2eHNuNTRAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjUjYXRyaW9sMzAwdS5nZmFuQGdtYWlsLmNvbWEyOWQ3OTRkMjdhMWU5OGY1ZjQ1ZmYyZWIzNjdiZDYyYjdhN2FiMzk&ctz=Asia%2FRiyadh&hl=ar&es=0

يمكنك الردّ على  
***@***.*** وعرض  
المزيد من التفاصيل  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc2MHI0Y2c5aTYxMjNlaGEyOGgxNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNzRxMzRnaGw3NTEzMGNocDY4cDQ4ZGhrNzExNDhjcTU3MHA0OGQyNTZoMzMyZHExOGNxZyByZXBseStiYWZ3dXc0ZHVzdGRpd2xsNGN4b2s2NmM3d2dpZGV2Ym5oaGc2eHNuNTRAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjUjYXRyaW9sMzAwdS5nZmFuQGdtYWlsLmNvbWEyOWQ3OTRkMjdhMWU5OGY1ZjQ1ZmYyZWIzNjdiZDYyYjdhN2FiMzk&ctz=Asia%2FRiyadh&hl=ar&es=0
حضورك اختياري.

~~//~~
‏دعوة من تقويم Google: https://calendar.google.com/calendar/

تلقّيت هذه الرسالة الإلكترونية لأنك ضيف في الحدث. لإيقاف تلقي التحديثات  
المستقبلية بشأن هذا الحدث، ارفض هذا الحدث.

تسمح إعادة توجيه هذه الدعوة لأي مستلم بإرسال رد إلى المُنظِّم وإضافة  
المستلِم إلى قائمة المدعوّوين، أو دعوة الآخرين بغض النظر عن حالة دعوتهم، أو  
تعديل الرد على الدعوة.

مزيد من المعلومات عن  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by 0569395312** [comment]
احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 0569395312** [comment]
احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 0569395312** [comment]
SA7180202461692222121016

احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jayasimhan** [comment]
Since some folks are looking for a solution to the issue here (although this repo is not for the browser itself), Here is the workaround from https://bugs.chromium.org/p/chromium/issues/detail?id=1473992#c8

**Step 0**: Close chrome.

**Step 1:** Open the Preferences file from the Chrome profile where you have this issue. For me, that was `Profile 1`
`cd ~/Library/Application\ Support/Google/Chrome/Profile 1`.  

**Step 2:** Remove any file_system_paths set in the configuration. It should look like this when you are done `file_system_paths:{}`. Save the file. Open Chrome.

**Comment by PR-JF** [comment]
Confirming also had the same issue in Chrome 116.0.5845.140 on Rocky 9 Linux. Devtools would close after about 7 seconds as soon as I launched it. Didn't matter which site. Had to revert to 115 to resolve.

In /var/log/messages I'd get the following error upon close:

google-chrome.desktop[9053]: [9048:9048:0905/120854.480028:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 18

**Comment by ChellappanRajan** [comment]
I am also encountering the same issue. Any help is appreciated.

**Comment by farrukh-taqveem** [comment]
> I am also encountering the same issue. Any help is appreciated.

**For Mac**
- First Find in which Profile it is happening. Default,  Profile 1 (Additional Profile), so on....
- Close Chrome. Right Click in the Drawer & click Quit. 

**For Default**
- `cd ~/Library/Application\ Support/Google/Chrome/Default`
- Open `Preferences` File (can use nano)
- Remove content from `file_system_paths` key (`file_system_paths:{}`)

Re-open Chrome

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
