### ISSUE TITLE
Inspect link is not showing in chrome://inspect/#devices

### ISSUE THREAD

**Issue by yugalshinde09** [GoogleChrome/developer.chrome.com#7255]
⚠️ This is for feature requests with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
<img width="525" alt="Chrome_inspect" src="https://github.com/GoogleChrome/developer.chrome.com/assets/65169448/d0078a1f-605d-45ab-969c-330e020e5e39">

**Comment by 0569395312** [comment]
Re: [GoogleChrome/developer.chrome.com] Inspect Eliment link is not showing  
in chrome://inspect/#devices (Issue #7255)
الجمعة 8 سبتمبر 2023













احصل على Outlook for Android


من:‏ yugalshinde09 ***@***.***&gt;

تاريخ الإرسال: الجمعة, سبتمبر 8, 2023 1:42:47 م
إلى: GoogleChrome/developer.chrome.com  
***@***.***&gt;

نسخة: Subscribed ***@***.***&gt;
الموضوع:‏ [GoogleChrome/developer.chrome.com] Inspect Eliment link is not  
showing in chrome://inspect/#devices (Issue #7255)





⚠️ This is for feature requests with the
https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind  
Google Chrome and other browsers), please use
https://crbug.com.
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always  
frustrated when [...]
Describe the solution you'd like
A clear and concise description of what you want to happen.
Describe alternatives you've considered
A clear and concise description of any alternative solutions or features  
you've considered.
Additional context
Add any other context or screenshots about the feature request here.

—
Reply to this email directly,
view it on GitHub, or
unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID:
***@***.***&gt;





المنظم
***@***.***
***@***.***

المدعوّون
GoogleChrome/developer.chrome.com‏
GoogleChrome/developer.chrome.com‏
Subscribed‏ - اختياري
عرض جميع معلومات المدعوّ  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4OHEzOGUxaDhvcGtjZDFrOGtwNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNjRxNDhjMWs2NHI0YWgxazhvbzM4YzFrNzBzMzJnaG84NTM0OGQxazcxMWphaDlpNmQzMCByZXBseStiYWZ3dXd5aGRrand3NWM2ZWdxNW4zZ2RiYXdzcGV2Ym5oaGhhNzR5Y3VAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjUjYXRyaW9sMzAwdS5nZmFuQGdtYWlsLmNvbTI3YWY3NWZiZGYzZWM1OWM5MWI3MDA1OWQxYWVlMTM2MTFmNjA1ZGY&ctz=Asia%2FRiyadh&hl=ar&es=0

يمكنك الردّ على  
***@***.*** وعرض  
المزيد من التفاصيل  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4OHEzOGUxaDhvcGtjZDFrOGtwNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNjRxNDhjMWs2NHI0YWgxazhvbzM4YzFrNzBzMzJnaG84NTM0OGQxazcxMWphaDlpNmQzMCByZXBseStiYWZ3dXd5aGRrand3NWM2ZWdxNW4zZ2RiYXdzcGV2Ym5oaGhhNzR5Y3VAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjUjYXRyaW9sMzAwdS5nZmFuQGdtYWlsLmNvbTI3YWY3NWZiZGYzZWM1OWM5MWI3MDA1OWQxYWVlMTM2MTFmNjA1ZGY&ctz=Asia%2FRiyadh&hl=ar&es=0
حضورك اختياري.

~~//~~
‏دعوة من تقويم Google: https://calendar.google.com/calendar/

تلقّيت هذه الرسالة الإلكترونية لأنك ضيف في الحدث. لإيقاف تلقي التحديثات  
المستقبلية بشأن هذا الحدث، ارفض هذا الحدث.

تسمح إعادة توجيه هذه الدعوة لأي مستلم بإرسال رد إلى المُنظِّم وإضافة  
المستلِم إلى قائمة المدعوّوين، أو دعوة الآخرين بغض النظر عن حالة دعوتهم، أو  
تعديل الرد على الدعوة.

مزيد من المعلومات عن  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by rachelandrew** [comment]
Please raise issues with Chrome itself in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) this tracker is for the content of the site at developer.chrome.com.
