### ISSUE TITLE
getAuthToken and oauth2 manifest documentation should mention failure modes

### ISSUE THREAD

**Issue by ericlaw1979** [GoogleChrome/developer.chrome.com#737]
The documentation for the chrome.identity APIs does not mention that they will fail when an admin has disabled the BrowserSignin policy or (Chromium 87+) when the APIs are called from Chromium or another non-Google Chrome browser.

Some discussion in https://bugs.chromium.org/p/chromium/issues/detail?id=1205882#c5

Chrome Dev points to this post which includes some context and a prototype polyfill: https://groups.google.com/a/chromium.org/g/embedder-dev/c/tGCJ3QNVzYE

**Comment by dotproto** [comment]
I agree that we should document the interaction with [BrowserSignin](https://chromeenterprise.google/policies/?policy=BrowserSignin). Thanks for calling out that `chrome.identity` fails in Chromium. I was not aware of that divergence and agree that we should document it. If you have any observations or guidance you can share here, it would be very welcome.

More broadly, I don't think we can or should cover non-Chrome Chromium based browsers. Our global namespace, documentation site URL, and web store name all highlight the Chrome-centric nature of the platform being provided. Since Chromium is a Google project, I think documenting divergence between Chrome and Chromium is within our charge, but we do not necessarily have insight into how other Chromium based browsers modify the extensions platform.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’ve moved to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at:
https://issuetracker.google.com/issues/324323521
