### ISSUE TITLE
Image size recommendations

### ISSUE THREAD

**Issue by Zwyx** [GoogleChrome/developer.chrome.com#7839]
**Describe the bug**

The section [Strategies for properly sizing images](https://developer.chrome.com/docs/lighthouse/performance/uses-responsive-images#strategies-for-properly-sizing-images) mentions:

> Ideally, your page should never serve images that are larger than the version that's rendered on the user's screen. Anything larger than that just results in wasted bytes and slows down page load time.

However, it seems that the usual recommendation is to create images that are four times bigger (2x on the width and 2x on the height), as we can read here:
- https://graphicdesign.stackexchange.com/questions/29850/do-i-need-to-create-my-images-at-twice-the-pixel-dimensions-on-a-retina-display
- https://stackoverflow.com/questions/22246292/when-to-use-double-size-images

**Comment by dstmarthe** [comment]
Hey there. 

The Lighthouse article is focused on image optimization in such a way that browser will not have to load a lot of information and will run faster. The two other recommendations you mention are graphic design based which is not necessarily geared towards performance or accessibility. The operative word in the Lighthouse article is "Ideally," because if ideally you want a fast website, you wouldn't serve images that are larger than the rendered version. But "ideally" if you want them to look better on Retina displays like the stack posts mention, then you would make them larger and then scale down.

So the Lighthouse article is justified with this section because it's properly sizing for performance.

Hope this clears it up for you.
