### ISSUE TITLE
Provide a way to set a filename for a code block

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#915]
### Is your feature request related to a problem? Please describe.
At the moment there isn't a good way for documentation editors to tag a code sample with a filename. 

### Describe the solution you'd like
I'd like to see a shortcode that we could use to tag a code block with a filename. I've included a rough sketch of how this might work below.

The source markdown + nunjucks
````njk
{% codeFile name="manifest.json" %}
```json
{ ... }
```
{% endCodeFile %}
````

The rendered output (code formatting on the code sample excluded)
```html
<figure>
<figcaption><strong>manifest.json</strong></figcaption>
<pre>{ ... }</pre>
```

### Describe alternatives you've considered
I've experimented with a couple of approaches, including using a bolded paragraph above the code sample and adding a [special comment](https://developer.chrome.com/docs/extensions/reference/runtime/#example-content-msg) at the top of the code block to denote the filename. Neither reads well or feels good in the final output.

### Additional context
@robdodson noted that the [label component](https://web.dev/handbook/web-dev-components/#labels) on web.dev fills this role.

**Comment by MichaelSolati** [comment]
I don't mind trying this one @robdodson but I'm not sure how to approach this.

**Comment by robdodson** [comment]
instead of wrapping the code block in a shortcode, i might see if we could do the same thing we do on web.dev.

https://web.dev/handbook/web-dev-components/#labels


It occurs to me that this probably doesn't need to be a paired shortcode, but maybe we would keep it as one for consistency between the two sites.

The Label shortcode would spit out a div that probably uses the `.type--caption` class.
We have a page level style that does this:

```
* + * { margin-top: ... }
```

So you'd need to write a selector that overrides that.

```
.code-label + pre { margin-top: get-size(200) }
```

I'm not sure if 200 is the right amount, I'm just using that to illustrate how you might override the default margin between elements.
